### ISSUE TITLE
提案：サイドコンテナ利用時のエラー抑制

### ISSUE THREAD

**Issue by nakanotti** [m0cchi/palworld-player-logger#3]
症状：
  サイドコンテナとして同時起動させると、rcon できる様になるまで ConnectionRefusedError を出力して終了します。
  restart: always にして、接続できるまで再起動させる事で対処可能ですが、あまりスマートではありません。

提案：
  初回起動だけでも、rcon 接続に長めのタイムアウト時間を設定できると幸いです。

**Comment by m0cchi** [comment]
https://github.com/m0cchi/palworld-player-logger/pull/4
